/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package to.the.moon

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        assertEquals(2, 1+1)
    }
}
