/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package to.the.moon.twitter

import com.twitter.hbc.ClientBuilder
import com.twitter.hbc.core.Constants
import com.twitter.hbc.core.HttpHosts
import com.twitter.hbc.core.endpoint.StatusesFilterEndpoint
import com.twitter.hbc.core.processor.StringDelimitedProcessor
import com.twitter.hbc.httpclient.BasicClient
import com.twitter.hbc.httpclient.auth.Authentication
import com.twitter.hbc.httpclient.auth.OAuth1
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.springframework.boot.CommandLineRunner
import org.springframework.stereotype.Component
import to.the.moon.sentimentanalysis.SentimentAnalysisService
import java.util.concurrent.LinkedBlockingDeque
import java.util.concurrent.TimeUnit.SECONDS


@Component
class TwitterStreamProducer(
    private val sentimentAnalysisService: SentimentAnalysisService,
    private val twitterConfiguration: TwitterConfiguration
) : CommandLineRunner {

    private val logger: Logger = LoggerFactory.getLogger(TwitterStreamProducer::class.java)

    private fun stream() {
        val (msgQueue, twitterClient) = createTwitterClient()
        while (!twitterClient.isDone) {
            msgQueue.poll(5, SECONDS)?.let { json ->
                Parser().tweet(json).also { tweet -> handleTweet(tweet) }
            }
        }
    }

    private fun handleTweet(tweet: Tweet) {
        val sentimentResult = sentimentAnalysisService.analyse(tweet.text)
        logger.info(tweet.text)
        logger.info("sentiment: $sentimentResult")
    }

    private fun createTwitterClient(): Pair<LinkedBlockingDeque<String>, BasicClient> {
        val msgQueue = LinkedBlockingDeque<String>(1000)
        val hoseBirdHosts = HttpHosts(Constants.STREAM_HOST)
        val hoseBirdEndpoint = StatusesFilterEndpoint()

        val terms: List<String> = twitterConfiguration.keywords
        hoseBirdEndpoint.trackTerms(terms)
        val hoseBirdAuth: Authentication = OAuth1(
            twitterConfiguration.ckey,
            twitterConfiguration.csecret,
            twitterConfiguration.token,
            twitterConfiguration.secret
        )
        val twitterClient = ClientBuilder()
            .name("streamingClient")
            .hosts(hoseBirdHosts)
            .authentication(hoseBirdAuth)
            .endpoint(hoseBirdEndpoint)
            .processor(StringDelimitedProcessor(msgQueue))
            .build()
        twitterClient.connect()
        return Pair(msgQueue, twitterClient)
    }

    override fun run(vararg args: String) = stream()
}