/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.4.20"
    id("org.springframework.boot") version "2.4.3"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
//    kotlin("jvm") version "1.4.20"
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    application
    id("application")
}
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}


repositories {
    mavenCentral()
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.twitter:hbc-core:2.2.0")
    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("ch.qos.logback:logback-core:1.2.3")
    implementation("edu.stanford.nlp:stanford-corenlp:4.0.0")
    implementation("edu.stanford.nlp:stanford-corenlp:4.0.0:models")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-json")
    implementation("org.apache.kafka:kafka-clients:2.4.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.12.1")
    implementation("com.fasterxml.jackson.core:jackson-core:2.12.1")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
}



tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> { kotlinOptions.jvmTarget = "11" }

application {
    // Define the main class for the application.
    mainClass.set("to.the.moon.AppKt")
}